COMP: Remove use of deprecated vtkThreshold API
This commit fixes removing use of API deprecated in kitware/vtk@62e5a71bf
(Add setters to vtkThreshold) and later removed in kitware/vtk@d933bb849
(vtkDeprecation: remove symbols deprecated in 9.1).

Error:

  SurfaceToolbox/DynamicModeler/Logic/vtkSlicerDynamicModelerSelectByPointsTool.cxx:423:22: error: ‘class vtkThreshold’ has no member named ‘ThresholdBetween’; did you mean ‘ThresholdType’?