COMP: Fix DynamicModeler/Logic/FastMarching build error on macOS
This commit fixes the following build error introduced
in 3e4245303 (ENH: Add SelectByPoints tool to DynamicModeler)

  /path/to/SurfaceToolbox/DynamicModeler/Logic/FastMarching/gw_core/../gw_maths/GW_MathsConfig.h:139:3: error: "Unknown architecture !"
          #error "Unknown architecture !"
           ^